name: Print Text from hellome.html

on:
  push:
    branches:
      - master
jobs:
  print-text:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: run node server.js
      runs: node server.js

